spring:
  application:
    name: zylos-hello-service

server:
  port: 8080
  shutdown: graceful

zylos:
  security:
    issuer-uri: ${ZYLOS_ISSUER_URI}
    jwk-set-uri: ${ZYLOS_JWK_SET_URI}
    expected-audience: zylos-internal-hello
    actor-chains:
      enabled: true
    opa:
      endpoint: ${ZYLOS_SECURITY_OPA_ENDPOINT}

management:
  server:
    port: 9000
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
      base-path: /actuator
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    git:
      mode: full
  metrics:
    tags:
      application: ${spring.application.name}
  opentelemetry:
    resource-attributes:
      service.name: ${spring.application.name}
      service.version: ${app.version:unknown}
      deployment.environment: ${spring.profiles.active}
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT}
  otlp:
    metrics:
      export:
        enabled: true
        url: ${OTEL_EXPORTER_OTLP_METRICS_ENDPOINT}

app:
  version: "@project.version@"

logging:
  level:
    root: INFO
    app.zylos: DEBUG
